In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


In [2]:
df_train = pd.read_csv("Data_for_Lab06/Activity_PCAAll_Train.csv")
df_test = pd.read_csv("Data_for_Lab06/Activity_PCAAll_Test.csv")
df_val = pd.read_csv("Data_for_Lab06/Activity_PCAAll_Validation.csv")

In [3]:
X_train = df_train.drop('Activity', axis=1)
y_train = df_train['Activity']

In [4]:
X_test = df_test.drop('Activity', axis=1)
y_test = df_test['Activity']

In [5]:
X_val = df_val.drop('Activity', axis=1)
y_val = df_val['Activity']

In [22]:
logistic_reg = LogisticRegression ( max_iter =1000)

logistic_reg . fit ( X_train , y_train )

y_test_pred = logistic_reg . predict ( X_test )
weights = logistic_reg . coef_

In [23]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_lr_orig=accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 343  13   0   0   0]
 [  0  15 366   0   0   0]
 [  0   0   0 342   1   1]
 [  0   0   0   0 280   1]
 [  0   0   0   3   0 306]]
Accuracy: 0.983495145631068
Precision (Micro): 0.983495145631068
Recall (Micro): 0.983495145631068
F1-score (Micro): 0.983495145631068
Precision (Macro): 0.9841753149289767
Recall (Macro): 0.9841719428522664
F1-score (Macro): 0.9841704779728376


In [8]:
logistic_reg = LogisticRegression ( max_iter =1000)

logistic_reg . fit ( X_train , y_train )

y_val_pred = logistic_reg . predict ( X_val )
weights = logistic_reg . coef_

In [9]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 343  10   0   0   2]
 [  0  15 366   0   0   0]
 [  0   0   0 344   1   0]
 [  0   0   0   1 280   0]
 [  0   0   0   1   1 307]]
Accuracy: 0.9849514563106796
Precision (Micro): 0.9849514563106796
Recall (Micro): 0.9849514563106796
F1-score (Micro): 0.9849514563106796
Precision (Macro): 0.9853599627777688
Recall (Macro): 0.985649557143867
F1-score (Macro): 0.9854940192518242


In [10]:
#svm linear

In [24]:

linear_svm = SVC(kernel="linear", C=1.0)
linear_svm.fit(X_train, y_train)
y_val_pred = linear_svm.predict(X_val)
y_test_pred = linear_svm.predict(X_test)

In [25]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_lin_orig=accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 345  11   0   0   0]
 [  0  17 364   0   0   0]
 [  0   0   0 344   0   0]
 [  0   0   0   0 281   0]
 [  0   0   0   3   1 305]]
Accuracy: 0.9844660194174757
Precision (Micro): 0.9844660194174757
Recall (Micro): 0.9844660194174757
F1-score (Micro): 0.9844660194174758
Precision (Macro): 0.9852522847113043
Recall (Macro): 0.9852561195340926
F1-score (Macro): 0.985222226259144


In [13]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 341  13   0   0   1]
 [  0  22 359   0   0   0]
 [  0   0   0 345   0   0]
 [  0   0   0   1 280   0]
 [  0   0   0   1   0 308]]
Accuracy: 0.9815533980582525
Precision (Micro): 0.9815533980582525
Recall (Micro): 0.9815533980582525
F1-score (Micro): 0.9815533980582525
Precision (Macro): 0.9825746280198834
Recall (Macro): 0.9826709388855929
F1-score (Macro): 0.9825785049971153


In [14]:
#svm poly kernal 

In [26]:
best_degree, best_val_acc = None, 0
for degree in [2, 3, 4, 5]:
  poly_svm = SVC(kernel="poly", degree=degree,C=1.0, gamma="scale")

  poly_svm.fit(X_train, y_train)
  val_acc = poly_svm.score(X_val, y_val)
  print(f"Degree={degree}, Validation Accuracy={val_acc:.4f}")
  if val_acc > best_val_acc:
    best_val_acc = val_acc
    best_degree = degree
print(f"\nBest Degree: {best_degree}")
best_poly_svm = SVC(kernel="poly", degree=best_degree,C=1.0, gamma="scale")

best_poly_svm.fit(X_train, y_train)
y_test_pred = best_poly_svm.predict(X_test)
y_val_pred = best_poly_svm.predict(X_val)

Degree=2, Validation Accuracy=0.9811
Degree=3, Validation Accuracy=0.9762
Degree=4, Validation Accuracy=0.9587
Degree=5, Validation Accuracy=0.9490

Best Degree: 2


In [27]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_poly_orig=accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[388   0   1   0   0   0]
 [  0 341  15   0   0   0]
 [  0  14 367   0   0   0]
 [  0   0   0 344   0   0]
 [  0   0   0   0 278   3]
 [  0   0   0   1   1 307]]
Accuracy: 0.9830097087378641
Precision (Micro): 0.9830097087378641
Recall (Micro): 0.9830097087378641
F1-score (Micro): 0.9830097087378641
Precision (Macro): 0.9837712873154122
Recall (Macro): 0.9835667365224601
F1-score (Macro): 0.9836644299268111


In [17]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[388   1   0   0   0   0]
 [  0 336  18   0   0   1]
 [  0  15 366   0   0   0]
 [  0   0   0 345   0   0]
 [  0   0   0   1 278   2]
 [  0   0   0   1   0 308]]
Accuracy: 0.9810679611650486
Precision (Micro): 0.9810679611650486
Recall (Micro): 0.9810679611650486
F1-score (Micro): 0.9810679611650486
Precision (Macro): 0.9820434105889739
Recall (Macro): 0.9817709496455921
F1-score (Macro): 0.9818937134508999


In [18]:
#gauusian rbf

In [28]:
rbf_svm = SVC(kernel="rbf", C=1.0, gamma="scale")
rbf_svm.fit(X_train, y_train)
y_val_pred = rbf_svm.predict(X_val)
y_test_pred = rbf_svm.predict(X_test)

In [29]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_rbf_orig = accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 345  11   0   0   0]
 [  0  14 367   0   0   0]
 [  0   0   0 344   0   0]
 [  0   0   0   0 280   1]
 [  0   0   0   2   0 307]]
Accuracy: 0.9864077669902913
Precision (Micro): 0.9864077669902913
Recall (Micro): 0.9864077669902913
F1-score (Micro): 0.9864077669902913
Precision (Macro): 0.9871458593912049
Recall (Macro): 0.9870540843334606
F1-score (Macro): 0.9870922616784741


In [21]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 338  16   0   0   1]
 [  0  16 365   0   0   0]
 [  0   0   0 345   0   0]
 [  0   0   0   1 280   0]
 [  0   0   0   0   0 309]]
Accuracy: 0.983495145631068
Precision (Micro): 0.983495145631068
Recall (Micro): 0.983495145631068
F1-score (Micro): 0.983495145631068
Precision (Macro): 0.9844485882281367
Recall (Macro): 0.9844265344231601
F1-score (Macro): 0.9844359337480707


In [31]:
data = {
"Dataset": ["pcaall"],
"Logistic Regression": [acc_lr_orig],
"SVM Linear": [acc_lin_orig],
"SVM Polynomial": [acc_poly_orig],
"SVM Gaussian": [acc_rbf_orig]
}
# Create DataFrame
df = pd.DataFrame(data)
df.set_index("Dataset", inplace=True)
# Print DataFrame
#print(f"Validation Accuracy Comparison\n{df}")
print(f"\nTest Accuracy Comparison\n{df}")
df.to_csv("pcaalldf.csv", index= False )


Test Accuracy Comparison
         Logistic Regression  SVM Linear  SVM Polynomial  SVM Gaussian
Dataset                                                               
pcaall              0.983495    0.984466         0.98301      0.986408
