In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


In [3]:
df_train = pd.read_csv("Data_for_Lab06/Activity_Train.csv")
df_test = pd.read_csv("Data_for_Lab06/Activity_Test.csv")
df_val = pd.read_csv("Data_for_Lab06/Activity_Validation.csv")

In [6]:
X_train = df_train.drop('Activity', axis=1)
y_train = df_train['Activity']

In [7]:
X_test = df_test.drop('Activity', axis=1)
y_test = df_test['Activity']

In [8]:
X_val = df_val.drop('Activity', axis=1)
y_val = df_val['Activity']

In [37]:
logistic_reg = LogisticRegression ( max_iter =1000)

logistic_reg . fit ( X_train , y_train )

y_test_pred = logistic_reg . predict ( X_test )
weights = logistic_reg . coef_

/home/user/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [39]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_lr_orig = accuracy_score(y_test, y_test_pred)
print("Accuracy:",acc_lr_orig)
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 343  13   0   0   0]
 [  0  15 366   0   0   0]
 [  0   0   0 342   1   1]
 [  0   0   0   0 280   1]
 [  0   0   0   3   0 306]]
Accuracy: 0.983495145631068
Precision (Micro): 0.983495145631068
Recall (Micro): 0.983495145631068
F1-score (Micro): 0.983495145631068
Precision (Macro): 0.9841753149289767
Recall (Macro): 0.9841719428522664
F1-score (Macro): 0.9841704779728376


In [19]:
logistic_reg = LogisticRegression ( max_iter =1000)

logistic_reg . fit ( X_train , y_train )

y_val_pred = logistic_reg . predict ( X_val )
weights = logistic_reg . coef_

/home/user/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [20]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 343  10   0   0   2]
 [  0  15 366   0   0   0]
 [  0   0   0 344   1   0]
 [  0   0   0   1 280   0]
 [  0   0   0   1   1 307]]
Accuracy: 0.9849514563106796
Precision (Micro): 0.9849514563106796
Recall (Micro): 0.9849514563106796
F1-score (Micro): 0.9849514563106796
Precision (Macro): 0.9853599627777688
Recall (Macro): 0.985649557143867
F1-score (Macro): 0.9854940192518242


In [21]:
#svm linear

In [40]:

linear_svm = SVC(kernel="linear", C=1.0)
linear_svm.fit(X_train, y_train)
y_val_pred = linear_svm.predict(X_val)
y_test_pred = linear_svm.predict(X_test)

In [41]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_lin_orig=accuracy_score(y_test, y_test_pred)
print("Accuracy:", acc_lin_orig)
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 345  11   0   0   0]
 [  0  17 364   0   0   0]
 [  0   0   0 344   0   0]
 [  0   0   0   0 281   0]
 [  0   0   0   3   1 305]]
Accuracy: 0.9844660194174757
Precision (Micro): 0.9844660194174757
Recall (Micro): 0.9844660194174757
F1-score (Micro): 0.9844660194174758
Precision (Macro): 0.9852522847113043
Recall (Macro): 0.9852561195340926
F1-score (Macro): 0.985222226259144


In [25]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 341  13   0   0   1]
 [  0  22 359   0   0   0]
 [  0   0   0 345   0   0]
 [  0   0   0   1 280   0]
 [  0   0   0   1   0 308]]
Accuracy: 0.9815533980582525
Precision (Micro): 0.9815533980582525
Recall (Micro): 0.9815533980582525
F1-score (Micro): 0.9815533980582525
Precision (Macro): 0.9825746280198834
Recall (Macro): 0.9826709388855929
F1-score (Macro): 0.9825785049971153


In [26]:
#svm poly kernal 

In [43]:
best_degree, best_val_acc = None, 0
for degree in [2, 3, 4, 5]:
  poly_svm = SVC(kernel="poly", degree=degree,C=1.0, gamma="scale")

  poly_svm.fit(X_train, y_train)
  val_acc = poly_svm.score(X_val, y_val)
  print(f"Degree={degree}, Validation Accuracy={val_acc:.4f}")
  if val_acc > best_val_acc:
    best_val_acc = val_acc
    best_degree = degree
print(f"\nBest Degree: {best_degree}")
best_poly_svm = SVC(kernel="poly", degree=best_degree,C=1.0, gamma="scale")

best_poly_svm.fit(X_train, y_train)
y_test_pred = best_poly_svm.predict(X_test)
y_val_pred = best_poly_svm.predict(X_val)

Degree=2, Validation Accuracy=0.9796
Degree=3, Validation Accuracy=0.9830
Degree=4, Validation Accuracy=0.9864
Degree=5, Validation Accuracy=0.9864

Best Degree: 4


In [44]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_poly_orig= accuracy_score(y_test, y_test_pred)
print("Accuracy:",acc_poly_orig)
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 347   9   0   0   0]
 [  0  14 367   0   0   0]
 [  0   0   0 344   0   0]
 [  0   0   0   0 281   0]
 [  0   0   0   1   1 307]]
Accuracy: 0.9878640776699029
Precision (Micro): 0.9878640776699029
Recall (Micro): 0.9878640776699029
F1-score (Micro): 0.9878640776699029
Precision (Macro): 0.9884730027228189
Recall (Macro): 0.9885835337316773
F1-score (Macro): 0.9885107457753355


In [42]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:",  accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 341  13   0   0   1]
 [  0  22 359   0   0   0]
 [  0   0   0 345   0   0]
 [  0   0   0   1 280   0]
 [  0   0   0   1   0 308]]
Accuracy: 0.9815533980582525
Precision (Micro): 0.9815533980582525
Recall (Micro): 0.9815533980582525
F1-score (Micro): 0.9815533980582525
Precision (Macro): 0.9825746280198834
Recall (Macro): 0.9826709388855929
F1-score (Macro): 0.9825785049971153


In [32]:
#gauusian rbf

In [45]:
rbf_svm = SVC(kernel="rbf", C=1.0, gamma="scale")
rbf_svm.fit(X_train, y_train)
y_val_pred = rbf_svm.predict(X_val)
y_test_pred = rbf_svm.predict(X_test)

In [46]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_rbf_orig= accuracy_score(y_test, y_test_pred)
print("Accuracy:",acc_rbf_orig)
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  1 333  22   0   0   0]
 [  0  23 358   0   0   0]
 [  0   0   0 344   0   0]
 [  0   0   0   0 278   3]
 [  0   0   0   1   2 306]]
Accuracy: 0.974757281553398
Precision (Micro): 0.974757281553398
Recall (Micro): 0.974757281553398
F1-score (Micro): 0.974757281553398
Precision (Macro): 0.9758640455481977
Recall (Macro): 0.9757734849851696
F1-score (Macro): 0.9758173447714862


In [35]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 321  32   0   0   2]
 [  0  25 356   0   0   0]
 [  0   0   0 345   0   0]
 [  0   0   0   1 279   1]
 [  0   0   0   1   5 303]]
Accuracy: 0.9674757281553398
Precision (Micro): 0.9674757281553398
Recall (Micro): 0.9674757281553398
F1-score (Micro): 0.9674757281553398
Precision (Macro): 0.9686830323005848
Recall (Macro): 0.968678940126973
F1-score (Macro): 0.9686330975262378


In [56]:
data = {
"Dataset": ["Original"],
"Logistic Regression": [acc_lr_orig],
"SVM Linear": [acc_lin_orig],
"SVM Polynomial": [acc_poly_orig],
"SVM Gaussian": [acc_rbf_orig]
}
# Create DataFrame
df = pd.DataFrame(data)
df.set_index("Dataset", inplace=True)
# Print DataFrame
#print(f"Validation Accuracy Comparison\n{df}")
print(f"\nTest Accuracy Comparison\n{df}")
df.to_csv("originaldf.csv", index= False )


Test Accuracy Comparison
          Logistic Regression  SVM Linear  SVM Polynomial  SVM Gaussian
Dataset                                                                
Original             0.983495    0.984466        0.987864      0.974757
