In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


In [2]:
df_train = pd.read_csv("Data_for_Lab06/Activity_PCA99_Train.csv")
df_test = pd.read_csv("Data_for_Lab06/Activity_PCA99_Test.csv")
df_val = pd.read_csv("Data_for_Lab06/Activity_PCA99_Validation.csv")

In [3]:
X_train = df_train.drop('Activity', axis=1)
y_train = df_train['Activity']

In [4]:
X_test = df_test.drop('Activity', axis=1)
y_test = df_test['Activity']

In [5]:
X_val = df_val.drop('Activity', axis=1)
y_val = df_val['Activity']

In [22]:
logistic_reg = LogisticRegression ( max_iter =1000)

logistic_reg . fit ( X_train , y_train )

y_test_pred = logistic_reg . predict ( X_test )
weights = logistic_reg . coef_

In [23]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_lr_orig=accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 345  11   0   0   0]
 [  0  21 360   0   0   0]
 [  0   0   0 342   1   1]
 [  0   0   0   0 281   0]
 [  0   0   0   3   0 306]]
Accuracy: 0.9820388349514563
Precision (Micro): 0.9820388349514563
Recall (Micro): 0.9820388349514563
F1-score (Micro): 0.9820388349514563
Precision (Macro): 0.9829123791129032
Recall (Macro): 0.9830767203344726
F1-score (Macro): 0.9829331465656025


In [8]:
logistic_reg = LogisticRegression ( max_iter =1000)

logistic_reg . fit ( X_train , y_train )

y_val_pred = logistic_reg . predict ( X_val )
weights = logistic_reg . coef_

In [9]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 335  18   0   0   2]
 [  0  17 364   0   0   0]
 [  0   0   0 344   1   0]
 [  0   0   0   1 280   0]
 [  0   0   0   1   1 307]]
Accuracy: 0.9800970873786408
Precision (Micro): 0.9800970873786408
Recall (Micro): 0.9800970873786408
F1-score (Micro): 0.9800970873786408
Precision (Macro): 0.980873181549104
Recall (Macro): 0.9810187979605959
F1-score (Macro): 0.9809420021395017


In [10]:
#svm linear

In [24]:

linear_svm = SVC(kernel="linear", C=1.0)
linear_svm.fit(X_train, y_train)
y_val_pred = linear_svm.predict(X_val)
y_test_pred = linear_svm.predict(X_test)

In [25]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_lin_orig=accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 344  12   0   0   0]
 [  0  18 363   0   0   0]
 [  0   0   0 344   0   0]
 [  0   0   0   0 281   0]
 [  0   0   0   3   0 306]]
Accuracy: 0.9839805825242719
Precision (Micro): 0.9839805825242719
Recall (Micro): 0.9839805825242719
F1-score (Micro): 0.9839805825242719
Precision (Macro): 0.9849384516587852
Recall (Macro): 0.9848898837465324
F1-score (Macro): 0.9848858579538793


In [13]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 336  18   0   0   1]
 [  0  22 359   0   0   0]
 [  0   0   0 345   0   0]
 [  0   0   0   1 280   0]
 [  0   0   0   0   0 309]]
Accuracy: 0.9796116504854369
Precision (Micro): 0.9796116504854369
Recall (Micro): 0.9796116504854369
F1-score (Micro): 0.9796116504854369
Precision (Macro): 0.9807810246802195
Recall (Macro): 0.9808628953709994
F1-score (Macro): 0.980813471176223


In [14]:
#svm poly kernal 

In [26]:
best_degree, best_val_acc = None, 0
for degree in [2, 3, 4, 5]:
  poly_svm = SVC(kernel="poly", degree=degree,C=1.0, gamma="scale")

  poly_svm.fit(X_train, y_train)
  val_acc = poly_svm.score(X_val, y_val)
  print(f"Degree={degree}, Validation Accuracy={val_acc:.4f}")
  if val_acc > best_val_acc:
    best_val_acc = val_acc
    best_degree = degree
print(f"\nBest Degree: {best_degree}")
best_poly_svm = SVC(kernel="poly", degree=best_degree,C=1.0, gamma="scale")

best_poly_svm.fit(X_train, y_train)
y_test_pred = best_poly_svm.predict(X_test)
y_val_pred = best_poly_svm.predict(X_val)

Degree=2, Validation Accuracy=0.9801
Degree=3, Validation Accuracy=0.9748
Degree=4, Validation Accuracy=0.9592
Degree=5, Validation Accuracy=0.9490

Best Degree: 2


In [27]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_poly_orig=accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[388   0   1   0   0   0]
 [  0 340  16   0   0   0]
 [  0  14 367   0   0   0]
 [  0   0   0 343   0   1]
 [  0   0   0   0 278   3]
 [  0   0   0   1   1 307]]
Accuracy: 0.9820388349514563
Precision (Micro): 0.9820388349514563
Recall (Micro): 0.9820388349514563
F1-score (Micro): 0.9820388349514563
Precision (Macro): 0.9828047002664207
Recall (Macro): 0.9826140756044216
F1-score (Macro): 0.9827015580878937


In [17]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[388   1   0   0   0   0]
 [  0 334  20   0   0   1]
 [  0  15 366   0   0   0]
 [  0   0   0 345   0   0]
 [  0   0   0   1 278   2]
 [  0   0   0   1   0 308]]
Accuracy: 0.9800970873786408
Precision (Micro): 0.9800970873786408
Recall (Micro): 0.9800970873786408
F1-score (Micro): 0.9800970873786408
Precision (Macro): 0.9811770419619187
Recall (Macro): 0.9808319825094419
F1-score (Macro): 0.9809816471384893


In [18]:
#gauusian rbf

In [28]:
rbf_svm = SVC(kernel="rbf", C=1.0, gamma="scale")
rbf_svm.fit(X_train, y_train)
y_val_pred = rbf_svm.predict(X_val)
y_test_pred = rbf_svm.predict(X_test)

In [29]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_rbf_orig=accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 344  12   0   0   0]
 [  0  16 365   0   0   0]
 [  0   0   0 344   0   0]
 [  0   0   0   0 280   1]
 [  0   0   0   2   0 307]]
Accuracy: 0.9849514563106796
Precision (Micro): 0.9849514563106796
Recall (Micro): 0.9849514563106796
F1-score (Micro): 0.9849514563106796
Precision (Macro): 0.985783036126867
Recall (Macro): 0.985711028900783
F1-score (Macro): 0.9857352037027752


In [21]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 336  18   0   0   1]
 [  0  16 365   0   0   0]
 [  0   0   0 345   0   0]
 [  0   0   0   1 280   0]
 [  0   0   0   0   0 309]]
Accuracy: 0.9825242718446602
Precision (Micro): 0.9825242718446602
Recall (Micro): 0.9825242718446602
F1-score (Micro): 0.9825242718446602
Precision (Macro): 0.9835720142749159
Recall (Macro): 0.9834875672870099
F1-score (Macro): 0.9835245356035691


In [30]:
data = {
"Dataset": ["pca99"],
"Logistic Regression": [acc_lr_orig],
"SVM Linear": [acc_lin_orig],
"SVM Polynomial": [acc_poly_orig],
"SVM Gaussian": [acc_rbf_orig]
}
# Create DataFrame
df = pd.DataFrame(data)
df.set_index("Dataset", inplace=True)
# Print DataFrame
#print(f"Validation Accuracy Comparison\n{df}")
print(f"\nTest Accuracy Comparison\n{df}")
df.to_csv("pca99df.csv", index= False )


Test Accuracy Comparison
         Logistic Regression  SVM Linear  SVM Polynomial  SVM Gaussian
Dataset                                                               
pca99               0.982039    0.983981        0.982039      0.984951


In [ ]:
#comparison

In [31]:
df1=pd.read_csv("originaldf.csv")
df2=pd.read_csv("scaledf.csv")
df3=pd.read_csv("pca99df.csv")
df4=pd.read_csv("pcaalldf.csv")
frames=[df1 , df2 , df3 ,df4]
combined_df_test=pd.concat(frames, ignore_index= True)
print(combined_df_test)

   Logistic Regression  SVM Linear  SVM Polynomial  SVM Gaussian
0             0.983495    0.984466        0.987864      0.974757
1             0.983981    0.984951        0.975243      0.981068
2             0.982039    0.983981        0.982039      0.984951
3             0.983495    0.984466        0.983010      0.986408
