In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


In [10]:
df_train = pd.read_csv("Data_for_Lab06/Activity_Scaled_Train.csv")
df_test = pd.read_csv("Data_for_Lab06/Activity_Scaled_Test.csv")
df_val = pd.read_csv("Data_for_Lab06/Activity_Scaled_Validation.csv")

In [11]:
X_train = df_train.drop('Activity', axis=1)
y_train = df_train['Activity']

In [12]:
X_test = df_test.drop('Activity', axis=1)
y_test = df_test['Activity']

In [13]:
X_val = df_val.drop('Activity', axis=1)
y_val = df_val['Activity']

In [34]:
logistic_reg = LogisticRegression ( max_iter =1000)

logistic_reg . fit ( X_train , y_train )

y_test_pred = logistic_reg . predict ( X_test )
weights = logistic_reg . coef_

/home/user/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [35]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_lr_orig = accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 340  16   0   0   0]
 [  0  12 369   0   0   0]
 [  0   0   0 344   0   0]
 [  0   0   0   1 280   0]
 [  0   0   0   4   0 305]]
Accuracy: 0.9839805825242719
Precision (Micro): 0.9839805825242719
Recall (Micro): 0.9839805825242719
F1-score (Micro): 0.9839805825242719
Precision (Macro): 0.9850040002976965
Recall (Macro): 0.9845094023505291
F1-score (Macro): 0.9847310427011989


In [32]:
logistic_reg = LogisticRegression ( max_iter =1000)

logistic_reg . fit ( X_train , y_train )

y_val_pred = logistic_reg . predict ( X_val )
weights = logistic_reg . coef_

/home/user/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [33]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 342  12   0   0   1]
 [  0  17 364   0   0   0]
 [  0   0   0 344   1   0]
 [  0   0   0   1 280   0]
 [  0   0   0   3   1 305]]
Accuracy: 0.9825242718446602
Precision (Micro): 0.9825242718446602
Recall (Micro): 0.9825242718446602
F1-score (Micro): 0.9825242718446602
Precision (Macro): 0.9831461534376605
Recall (Macro): 0.9832264342855574
F1-score (Macro): 0.9831667321718841


In [18]:
#svm linear

In [36]:

linear_svm = SVC(kernel="linear", C=1.0)
linear_svm.fit(X_train, y_train)
y_val_pred = linear_svm.predict(X_val)
y_test_pred = linear_svm.predict(X_test)

In [37]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_lin_orig=accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 344  12   0   0   0]
 [  0  14 367   0   0   0]
 [  0   0   0 344   0   0]
 [  0   0   0   1 280   0]
 [  0   0   0   3   1 305]]
Accuracy: 0.9849514563106796
Precision (Micro): 0.9849514563106796
Recall (Micro): 0.9849514563106796
F1-score (Micro): 0.9849514563106796
Precision (Macro): 0.9856964356474238
Recall (Macro): 0.9855071708878889
F1-score (Macro): 0.9855868640325675


In [21]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[389   0   0   0   0   0]
 [  0 339  15   0   0   1]
 [  0  21 360   0   0   0]
 [  0   0   0 344   1   0]
 [  0   0   0   1 280   0]
 [  0   0   0   2   1 306]]
Accuracy: 0.9796116504854369
Precision (Micro): 0.9796116504854369
Recall (Micro): 0.9796116504854369
F1-score (Micro): 0.9796116504854369
Precision (Macro): 0.9804452676589447
Recall (Macro): 0.9806075766297738
F1-score (Macro): 0.9805050417525903


In [22]:
#svm poly kernal 

In [38]:
best_degree, best_val_acc = None, 0
for degree in [2, 3, 4, 5]:
  poly_svm = SVC(kernel="poly", degree=degree,C=1.0, gamma="scale")

  poly_svm.fit(X_train, y_train)
  val_acc = poly_svm.score(X_val, y_val)
  print(f"Degree={degree}, Validation Accuracy={val_acc:.4f}")
  if val_acc > best_val_acc:
    best_val_acc = val_acc
    best_degree = degree
print(f"\nBest Degree: {best_degree}")
best_poly_svm = SVC(kernel="poly", degree=best_degree,C=1.0, gamma="scale")

best_poly_svm.fit(X_train, y_train)
y_test_pred = best_poly_svm.predict(X_test)
y_val_pred = best_poly_svm.predict(X_val)

Degree=2, Validation Accuracy=0.9738
Degree=3, Validation Accuracy=0.9655
Degree=4, Validation Accuracy=0.9364
Degree=5, Validation Accuracy=0.9194

Best Degree: 2


In [39]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_poly_orig = accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[388   0   1   0   0   0]
 [  1 336  19   0   0   0]
 [  0  19 362   0   0   0]
 [  0   0   0 344   0   0]
 [  0   1   0   0 273   7]
 [  0   3   0   0   0 306]]
Accuracy: 0.9752427184466019
Precision (Micro): 0.9752427184466019
Recall (Micro): 0.9752427184466019
F1-score (Micro): 0.9752427184466019
Precision (Macro): 0.9764403692250173
Recall (Macro): 0.9755337125789568
F1-score (Macro): 0.975942969758441


In [25]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[388   1   0   0   0   0]
 [  1 333  20   0   0   1]
 [  0  20 361   0   0   0]
 [  0   1   0 343   1   0]
 [  0   1   0   2 276   2]
 [  0   1   0   0   3 305]]
Accuracy: 0.9737864077669903
Precision (Micro): 0.9737864077669903
Recall (Micro): 0.9737864077669903
F1-score (Micro): 0.9737864077669903
Precision (Macro): 0.9746476502268058
Recall (Macro): 0.9744047261720626
F1-score (Macro): 0.9745240041701276


In [26]:
#gauusian rbf

In [40]:
rbf_svm = SVC(kernel="rbf", C=1.0, gamma="scale")
rbf_svm.fit(X_train, y_train)
y_val_pred = rbf_svm.predict(X_val)
y_test_pred = rbf_svm.predict(X_test)

In [41]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
acc_rbf_orig= accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision (Micro):", precision_score(y_test, y_test_pred, average="micro"))
print("Recall (Micro):", recall_score(y_test, y_test_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_test, y_test_pred, average="micro"))

print("Precision (Macro):", precision_score(y_test, y_test_pred, average="macro"))
print("Recall (Macro):", recall_score(y_test, y_test_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_test, y_test_pred, average="macro"))

Confusion Matrix:
[[388   0   0   0   1   0]
 [  0 341  15   0   0   0]
 [  0  21 360   0   0   0]
 [  0   0   0 344   0   0]
 [  0   0   0   0 281   0]
 [  0   0   0   1   1 307]]
Accuracy: 0.9810679611650486
Precision (Micro): 0.9810679611650486
Recall (Micro): 0.9810679611650486
F1-score (Micro): 0.9810679611650486
Precision (Macro): 0.9820038769570697
Recall (Macro): 0.9822839787177194
F1-score (Macro): 0.9821184073300886


In [29]:
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("Accuracy:", accuracy_score(y_val, y_val_pred))
print("Precision (Micro):", precision_score(y_val, y_val_pred, average="micro"))
print("Recall (Micro):", recall_score(y_val, y_val_pred, average="micro"))
print("F1-score (Micro):", f1_score(y_val, y_val_pred, average="micro"))

print("Precision (Macro):", precision_score(y_val, y_val_pred, average="macro"))
print("Recall (Macro):", recall_score(y_val, y_val_pred, average="macro"))
print("F1-score (Macro):", f1_score(y_val, y_val_pred, average="macro"))

Confusion Matrix:
[[386   0   0   0   3   0]
 [  1 335  18   0   0   1]
 [  0  19 362   0   0   0]
 [  0   0   0 342   3   0]
 [  0   0   0   1 280   0]
 [  0   0   0   0   1 308]]
Accuracy: 0.9771844660194174
Precision (Micro): 0.9771844660194174
Recall (Micro): 0.9771844660194174
F1-score (Micro): 0.9771844660194174
Precision (Macro): 0.9776388902471412
Recall (Macro): 0.9784317510291266
F1-score (Macro): 0.9780138942703944


In [45]:
data = {
"Dataset": ["scaled"],
"Logistic Regression": [acc_lr_orig],
"SVM Linear": [acc_lin_orig],
"SVM Polynomial": [acc_poly_orig],
"SVM Gaussian": [acc_rbf_orig]
}
# Create DataFrame
df = pd.DataFrame(data)
df.set_index("Dataset", inplace=True)
# Print DataFrame
#print(f"Validation Accuracy Comparison\n{df}")
print(f"\nTest Accuracy Comparison\n{df}")
df.to_csv("scaledf.csv", index= False )


Test Accuracy Comparison
         Logistic Regression  SVM Linear  SVM Polynomial  SVM Gaussian
Dataset                                                               
scaled              0.983981    0.984951        0.975243      0.981068
