# NumPy Basic Operations Examples
This notebook demonstrates multiplication, division, argmax, and dimension operations using NumPy.


In [2]:
import numpy as np
print('NumPy Version:', np.__version__)

NumPy Version: 2.0.2


## 1. Scalar Operations

In [ ]:
x = 5
y = 2
print('Multiplication:', x * y)
print('Division:', x / y)

Multiplication: 10
Division: 2.5


## 2. 1D Array Operations

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('Element-wise Multiplication:', a * b)
print('Element-wise Division:', a / b)
print('Scalar Multiplication:', a * 2)

Element-wise Multiplication: [ 4 10 18]
Element-wise Division: [0.25 0.4  0.5 ]
Scalar Multiplication: [2 4 6]


## 3. 2D Array Operations

In [ ]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
B = np.array([[2, 2],
              [2, 2],
              [2, 2]])
print('Shape of A:', A.shape)
print('Element-wise Multiplication:\n', A * B)
print('Scalar Multiplication:\n', A * 3)
print('Division by Scalar:\n', A / 2)

Shape of A: (3, 2)
Element-wise Multiplication:
 [[ 2  4]
 [ 6  8]
 [10 12]]
Scalar Multiplication:
 [[ 3  6]
 [ 9 12]
 [15 18]]
Division by Scalar:
 [[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


## 4. Argmax Operation

In [3]:
x = np.array([0.2, 0.8, 0.5])
print('Argmax (1D):', np.argmax(x))

scores = np.array([[0.1, 0.7, 0.2],
                   [0.9, 0.05, 0.05],
                   [0.3, 0.4, 0.3]])
print('Argmax (Row-wise):', np.argmax(scores, axis=1))

Argmax (1D): 1
Argmax (Row-wise): [1 0 1]


## 5. Dimension Change Operations

In [ ]:
x = np.array([1, 2, 3])
print('Original Shape:', x.shape)

x_row = x.reshape(1, 3)
print('Row Vector Shape:', x_row.shape)

x_col = x.reshape(3, 1)
print('Column Vector Shape:', x_col.shape)

A = np.array([[1, 2, 3],
              [4, 5, 6]])
print('Transpose:\n', A.T)

posteriors = np.array([[0.1, 0.2, 0.3],
                        [0.4, 0.5, 0.6]])
print('Original Shape:', posteriors.shape)
print('Swapped Axes Shape:', np.swapaxes(posteriors, 0, 1).shape)

Original Shape: (3,)
Row Vector Shape: (1, 3)
Column Vector Shape: (3, 1)
Transpose:
 [[1 4]
 [2 5]
 [3 6]]
Original Shape: (2, 3)
Swapped Axes Shape: (3, 2)


## 6. Mini Bayes-like Example

In [ ]:
likelihoods = np.array([[0.2, 0.5],
                        [0.6, 0.1],
                        [0.3, 0.4]])

priors = np.array([0.7, 0.3])

numerators = likelihoods * priors
print('\nNumerators:\n', numerators)

tot_prob = np.sum(numerators, axis=1).reshape(-1, 1)
print('\nTotal Probability:\n', tot_prob)

posteriors = numerators/tot_prob
print('\nPosteriors:\n', posteriors)

predictions = np.argmax(posteriors, axis=1)
print('\nPredicted Classes:', predictions)


Numerators:
 [[0.14 0.15]
 [0.42 0.03]
 [0.21 0.12]]

Total Probability:
 [[0.29]
 [0.45]
 [0.33]]

Posteriors:
 [[0.48275862 0.51724138]
 [0.93333333 0.06666667]
 [0.63636364 0.36363636]]

Predicted Classes: [1 0 0]
